### ISSUE TITLE
Cannot find user data

### ISSUE THREAD

**Issue by lfender6445** [raysrashmi/ruby-stackoverflow#13]
I am am unable to find data for valid users
```
[11] pry(#<AutoPilot::API>)> b = RubyStackoverflow.users(inname: 'jon-skeet')
=> #<RubyStackoverflow::Client::ResponseData:0x007fc612d595a0 @data=[], @has_more=false>
[12] pry(#<AutoPilot::API>)> b.data
=> []
```
here is user profile

http://stackoverflow.com/users/22656/jon-skeet

any idea why? I am able to reproduce this for users with hyphens in their names

**Comment by raysrashmi** [comment]
@lfender6445  Actually so the inname parameter is a substring in user's  display name. If you do like RubyStackoverflow.users(inname: ' jonn skeet') you will get the results.

**Comment by lfender6445** [comment]
ahh i see, so I should be using `{name: 'jon-skeet'}` to grab user profile info yes?

**Comment by raysrashmi** [comment]
No there is no "name" parameter https://api.stackexchange.com/docs/users so you should pass "inname"

**Comment by lfender6445** [comment]
yes

```
reputation – reputation
creation – creation_date
name – display_name
modified – last_modified_date
```

on that page you linked there is supported name param - in this sense, 'inname' i think refers to 'jon' being in 'jon skeet' so it will return more results than I want

if I run `b = RubyStackoverflow.users(inname: 'jon-skeet')` I get jon skeet as first result, which is what I want.

**Comment by lfender6445** [comment]
wow - this is weird - `RubyStackoverflow.users(name: 'test')` is a jon skeet result as well. such bizarre behavior.
