### ISSUE TITLE
requesting new gem build

### ISSUE THREAD

**Issue by lfender6445** [raysrashmi/ruby-stackoverflow#8]
https://github.com/raysrashmi/ruby-stackoverflow/blob/master/lib/ruby-stackoverflow/client/response_data.rb#L12

I'd like to use the `:has_more` attribute which is missing from latest build

https://github.com/raysrashmi/ruby-stackoverflow/blob/master/lib/ruby-stackoverflow/client/response_data.rb

would you mind pushing 0.0.3 to rubygems?

**Comment by raysrashmi** [comment]
Released a new version :heart:

**Comment by lfender6445** [comment]
thanks so much! your work is very useful to me right now, i will be using it one of my projects.
